// <auto-generated />
using System;
using InteractiveMap.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InteractiveMap.Infrastructure.Migrations.Map
{
    [DbContext(typeof(MapContext))]
    [Migration("20220608023413_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("InteractiveMap.Core.Entities.Mark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("LayerType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Marks", (string)null);
                });

            modelBuilder.Entity("InteractiveMap.Core.Entities.UserMark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("LayerType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserMarks", (string)null);
                });

            modelBuilder.Entity("InteractiveMap.Core.Entities.Mark", b =>
                {
                    b.OwnsOne("InteractiveMap.Core.ValueObjects.Position", "Position", b1 =>
                        {
                            b1.Property<int>("MarkId")
                                .HasColumnType("INTEGER");

                            b1.Property<double>("Latitude")
                                .HasColumnType("REAL");

                            b1.Property<double>("Longitude")
                                .HasColumnType("REAL");

                            b1.HasKey("MarkId");

                            b1.ToTable("Marks");

                            b1.WithOwner()
                                .HasForeignKey("MarkId");
                        });

                    b.Navigation("Position");
                });

            modelBuilder.Entity("InteractiveMap.Core.Entities.UserMark", b =>
                {
                    b.OwnsOne("InteractiveMap.Core.ValueObjects.Position", "Position", b1 =>
                        {
                            b1.Property<int>("UserMarkId")
                                .HasColumnType("INTEGER");

                            b1.Property<double>("Latitude")
                                .HasColumnType("REAL");

                            b1.Property<double>("Longitude")
                                .HasColumnType("REAL");

                            b1.HasKey("UserMarkId");

                            b1.ToTable("UserMarks");

                            b1.WithOwner()
                                .HasForeignKey("UserMarkId");
                        });

                    b.Navigation("Position");
                });
#pragma warning restore 612, 618
        }
    }
}
